version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_HOST=db
      - DB_NAME=TripOrganizer
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_KEY=${JWT_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - FRONTEND_URL=${FRONTEND_URL}
      - SSL_PASSWORD=${SSL_PASSWORD}
    volumes:
      - ssl_certs:/etc/ssl/certs
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - tripmarket_network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=TripOrganizer
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - tripmarket_network

volumes:
  postgres_data:
  ssl_certs:


networks:
  tripmarket_network:
    driver: bridge
